version: '3.8'

services:
  backend:
    container_name: glowguide_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: >
      command: >
        sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
