version: '3.8'

services:
  backend:
    container_name: glowguide_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    command: >
      command: >
        sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
