name: CI/CD for FastAPI to Azure Web App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -f Dockerfile \
            -t ${{ secrets.ACR_NAME }}.azurecr.io/glowguidefastapi:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/glowguidefastapi:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp config container set \
              --resource-group glowguideResourceGroup \
              --name glowguide-backend-7514 \
              --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/glowguidefastapi:${{ github.sha }} \
              --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io \
              --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
              --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}

            az webapp config appsettings set \
              --resource-group glowguideResourceGroup \
              --name glowguide-backend-7514 \
              --settings WEBSITES_PORT=8000

            az webapp restart \
              --resource-group glowguideResourceGroup \
              --name glowguide-backend-7514
